services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    restart: unless-stopped
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2

  db:
    image: postgres:17.6
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local-dev

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
